In [1]:
import pandas as pd

In [5]:
data=[1,2,3,4,5]
index=['a','b','c','d','e']
series=pd.Series(data)
print(series)
series=pd.Series(data,index)
print(series)

0    1
1    2
2    3
3    4
4    5
dtype: int64
a    1
b    2
c    3
d    4
e    5
dtype: int64

In [8]:
obesity_data=pd.read_csv('./obesity_prediction.csv')

In [11]:
obesity_data.head()

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
0,Female,21.0,1.62,64.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight
1,Female,21.0,1.52,56.0,yes,no,3.0,3.0,Sometimes,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
2,Male,23.0,1.80,77.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight
3,Male,27.0,1.80,87.0,no,no,3.0,3.0,Sometimes,no,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I
4,Male,22.0,1.78,89.8,no,no,2.0,1.0,Sometimes,no,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II

In [13]:
obesity_data.tail()

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
2106,Female,20.976842,1.710730,131.408528,yes,yes,3.0,3.0,Sometimes,no,1.728139,no,1.676269,0.906247,Sometimes,Public_Transportation,Obesity_Type_III
2107,Female,21.982942,1.748584,133.742943,yes,yes,3.0,3.0,Sometimes,no,2.005130,no,1.341390,0.599270,Sometimes,Public_Transportation,Obesity_Type_III
2108,Female,22.524036,1.752206,133.689352,yes,yes,3.0,3.0,Sometimes,no,2.054193,no,1.414209,0.646288,Sometimes,Public_Transportation,Obesity_Type_III
2109,Female,24.361936,1.739450,133.346641,yes,yes,3.0,3.0,Sometimes,no,2.852339,no,1.139107,0.586035,Sometimes,Public_Transportation,Obesity_Type_III
2110,Female,23.664709,1.738836,133.472641,yes,yes,3.0,3.0,Sometimes,no,2.863513,no,1.026452,0.714137,Sometimes,Public_Transportation,Obesity_Type_III

In [14]:
obesity_data.sample()

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
928,Male,19.627,1.815409,85.302146,yes,yes,2.987148,3.483449,Sometimes,no,2.359246,no,2.060415,0.598999,Sometimes,Public_Transportation,Overweight_Level_I

In [21]:
obesity_data.sample(10)

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
1487,Female,39.126310,1.562889,76.659490,yes,yes,2.000000,3.000000,Sometimes,no,1.440526,no,0.000000,0.000000,Sometimes,Automobile,Obesity_Type_I
1444,Female,23.652435,1.562724,80.535698,yes,yes,2.000000,1.000000,Sometimes,no,2.000000,no,0.389717,0.000000,no,Public_Transportation,Obesity_Type_I
705,Female,22.993680,1.741377,54.877111,yes,yes,3.000000,3.000000,Frequently,no,2.009796,no,2.000000,0.071317,no,Public_Transportation,Insufficient_Weight
1377,Male,29.633715,1.834842,105.199360,yes,yes,2.805533,3.000000,Sometimes,no,1.882847,no,2.000000,0.707780,Sometimes,Automobile,Obesity_Type_I
1633,Male,30.475248,1.801368,121.094257,yes,yes,2.328469,3.000000,Sometimes,no,2.001208,no,0.800487,0.176678,Sometimes,Automobile,Obesity_Type_II
1787,Male,24.511445,1.852664,121.310257,yes,yes,2.906269,2.894142,Sometimes,no,2.435489,no,1.266739,0.362160,Sometimes,Public_Transportation,Obesity_Type_II
1888,Female,25.989938,1.644199,105.036075,yes,yes,3.000000,3.000000,Sometimes,no,2.310076,no,0.071150,0.733085,Sometimes,Public_Transportation,Obesity_Type_III
562,Female,17.000433,1.584951,44.411801,no,yes,2.737762,3.000000,Sometimes,no,2.310921,no,2.240714,1.592570,Sometimes,Public_Transportation,Insufficient_Weight
1938,Female,21.413498,1.719900,133.886031,yes,yes,3.000000,3.000000,Sometimes,no,2.417520,no,1.556155,0.873936,Sometimes,Public_Transportation,Obesity_Type_III
1290,Male,22.975526,1.701986,95.000000,yes,yes,2.000000,3.000000,Sometimes,no,2.021270,no,1.814869,1.066603,no,Public_Transportation,Obesity_Type_I

In [18]:
obesity_data.sample(10,random_state=30)

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
6,Female,23.000000,1.500000,55.000000,yes,yes,3.000000,3.000000,Sometimes,no,2.000000,no,1.000000,0.000000,Sometimes,Motorbike,Normal_Weight
1077,Female,23.728707,1.663509,80.000000,yes,yes,2.000000,3.000000,Sometimes,no,2.137550,no,0.000000,0.124977,no,Public_Transportation,Overweight_Level_II
2100,Female,25.777565,1.628205,107.378702,yes,yes,3.000000,3.000000,Sometimes,no,2.506631,no,0.025787,0.484165,Sometimes,Public_Transportation,Obesity_Type_III
1618,Male,41.000000,1.750000,115.806977,yes,yes,2.000000,2.701521,Sometimes,no,1.142644,no,0.514225,0.000000,no,Automobile,Obesity_Type_II
1347,Male,22.352025,1.754711,105.000706,yes,yes,2.871137,3.000000,Sometimes,no,2.627569,no,1.000000,0.000000,Sometimes,Public_Transportation,Obesity_Type_I
620,Female,19.931667,1.653209,49.026214,no,no,2.530066,3.000000,Sometimes,no,1.965237,no,2.000000,1.000000,Sometimes,Public_Transportation,Insufficient_Weight
1276,Male,19.089595,1.700164,99.204695,yes,yes,2.000000,2.119826,Sometimes,no,2.000000,no,0.000000,1.882539,no,Public_Transportation,Obesity_Type_I
1381,Female,33.226808,1.557943,77.647716,yes,yes,2.020910,2.093831,Sometimes,no,1.506518,no,0.000000,0.000000,Sometimes,Automobile,Obesity_Type_I
353,Female,24.000000,1.600000,51.000000,yes,yes,1.000000,3.000000,Sometimes,no,2.000000,no,0.000000,1.000000,Sometimes,Automobile,Normal_Weight
220,Female,21.000000,1.750000,78.000000,yes,no,2.000000,3.000000,Frequently,no,2.000000,yes,0.000000,2.000000,Frequently,Public_Transportation,Overweight_Level_I

In [24]:
obesity_data.columns.tolist()

['Gender',
 'Age',
 'Height',
 'Weight',
 'family_history',
 'FAVC',
 'FCVC',
 'NCP',
 'CAEC',
 'SMOKE',
 'CH2O',
 'SCC',
 'FAF',
 'TUE',
 'CALC',
 'MTRANS',
 'Obesity']

In [25]:
obesity_data.describe()

,Age,Height,Weight,FCVC,NCP,CH2O,FAF,TUE
count,2111.000000,2111.000000,2111.000000,2111.000000,2111.000000,2111.000000,2111.000000,2111.000000
mean,24.312600,1.701677,86.586058,2.419043,2.685628,2.008011,1.010298,0.657866
std,6.345968,0.093305,26.191172,0.533927,0.778039,0.612953,0.850592,0.608927
min,14.000000,1.450000,39.000000,1.000000,1.000000,1.000000,0.000000,0.000000
25%,19.947192,1.630000,65.473343,2.000000,2.658738,1.584812,0.124505,0.000000
50%,22.777890,1.700499,83.000000,2.385502,3.000000,2.000000,1.000000,0.625350
75%,26.000000,1.768464,107.430682,3.000000,3.000000,2.477420,1.666678,1.000000
max,61.000000,1.980000,173.000000,3.000000,4.000000,3.000000,3.000000,2.000000

In [26]:
obesity_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2111 entries, 0 to 2110
Data columns (total 17 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Gender          2111 non-null   object
 1   Age             2111 non-null   float64
 2   Height          2111 non-null   float64
 3   Weight          2111 non-null   float64
 4   family_history  2111 non-null   object
 5   FAVC            2111 non-null   object
 6   FCVC            2111 non-null   float64
 7   NCP             2111 non-null   float64
 8   CAEC            2111 non-null   object
 9   SMOKE           2111 non-null   object
 10  CH2O            2111 non-null   float64
 11  SCC             2111 non-null   object
 12  FAF             2111 non-null   float64
 13  TUE             2111 non-null   float64
 14  CALC            2111 non-null   object
 15  MTRANS          2111 non-null   object
 16  Obesity         2111 non-null   object
dtypes: float64(8), object(9)
memory usage: 280.5+ KB

In [27]:
obesity_data.loc[[0],['Age']]

    Age
0  21.0

In [29]:
obesity_data.loc[[0,10],['Age']]

     Age
0   21.0
10  26.0

In [31]:
obesity_data.loc[0:10 ,['Age']]

     Age
0   21.0
1   21.0
2   23.0
3   27.0
4   22.0
5   29.0
6   23.0
7   22.0
8   24.0
9   22.0
10  26.0

In [32]:
obesity_data.loc[0:10 ,['Age','Height','Weight']]

     Age  Height  Weight
0   21.0    1.62    64.0
1   21.0    1.52    56.0
2   23.0    1.80    77.0
3   27.0    1.80    87.0
4   22.0    1.78    89.8
5   29.0    1.62    53.0
6   23.0    1.50    55.0
7   22.0    1.64    53.0
8   24.0    1.78    64.0
9   22.0    1.72    68.0
10  26.0    1.85   105.0

In [33]:
obesity_data.loc[:,'Age':]

,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
0,21.000000,1.620000,64.000000,yes,no,2.0,3.0,Sometimes,no,2.000000,no,0.000000,1.000000,no,Public_Transportation,Normal_Weight
1,21.000000,1.520000,56.000000,yes,no,3.0,3.0,Sometimes,yes,3.000000,yes,3.000000,0.000000,Sometimes,Public_Transportation,Normal_Weight
2,23.000000,1.800000,77.000000,yes,no,2.0,3.0,Sometimes,no,2.000000,no,2.000000,1.000000,Frequently,Public_Transportation,Normal_Weight
3,27.000000,1.800000,87.000000,no,no,3.0,3.0,Sometimes,no,2.000000,no,2.000000,0.000000,Frequently,Walking,Overweight_Level_I
4,22.000000,1.780000,89.800000,no,no,2.0,1.0,Sometimes,no,2.000000,no,0.000000,0.000000,Sometimes,Public_Transportation,Overweight_Level_II
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2106,20.976842,1.710730,131.408528,yes,yes,3.0,3.0,Sometimes,no,1.728139,no,1.676269,0.906247,Sometimes,Public_Transportation,Obesity_Type_III
2107,21.982942,1.748584,133.742943,yes,yes,3.0,3.0,Sometimes,no,2.005130,no,1.341390,0.599270,Sometimes,Public_Transportation,Obesity_Type_III
2108,22.524036,1.752206,133.689352,yes,yes,3.0,3.0,Sometimes,no,2.054193,no,1.414209,0.646288,Sometimes,Public_Transportation,Obesity_Type_III
2109,24.361936,1.739450,133.346641,yes,yes,3.0,3.0,Sometimes,no,2.852339,no,1.139107,0.586035,Sometimes,Public_Transportation,Obesity_Type_III
2110,23.664709,1.738836,133.472641,yes,yes,3.0,3.0,Sometimes,no,2.863513,no,1.026452,0.714137,Sometimes,Public_Transportation,Obesity_Type_III

In [34]:
obesity_data.loc[:,'Age':'FAF']

,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF
0,21.000000,1.620000,64.000000,yes,no,2.0,3.0,Sometimes,no,2.000000,no,0.000000
1,21.000000,1.520000,56.000000,yes,no,3.0,3.0,Sometimes,yes,3.000000,yes,3.000000
2,23.000000,1.800000,77.000000,yes,no,2.0,3.0,Sometimes,no,2.000000,no,2.000000
3,27.000000,1.800000,87.000000,no,no,3.0,3.0,Sometimes,no,2.000000,no,2.000000
4,22.000000,1.780000,89.800000,no,no,2.0,1.0,Sometimes,no,2.000000,no,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...
2106,20.976842,1.710730,131.408528,yes,yes,3.0,3.0,Sometimes,no,1.728139,no,1.676269
2107,21.982942,1.748584,133.742943,yes,yes,3.0,3.0,Sometimes,no,2.005130,no,1.341390
2108,22.524036,1.752206,133.689352,yes,yes,3.0,3.0,Sometimes,no,2.054193,no,1.414209
2109,24.361936,1.739450,133.346641,yes,yes,3.0,3.0,Sometimes,no,2.852339,no,1.139107
2110,23.664709,1.738836,133.472641,yes,yes,3.0,3.0,Sometimes,no,2.863513,no,1.026452

In [35]:
obesity_data.iloc[0:10,0:5]

   Gender   Age  Height  Weight family_history
0  Female  21.0    1.62    64.0            yes
1  Female  21.0    1.52    56.0            yes
2    Male  23.0    1.80    77.0            yes
3    Male  27.0    1.80    87.0             no
4    Male  22.0    1.78    89.8             no
5    Male  29.0    1.62    53.0             no
6  Female  23.0    1.50    55.0            yes
7    Male  22.0    1.64    53.0             no
8    Male  24.0    1.78    64.0            yes
9    Male  22.0    1.72    68.0            yes

In [36]:
obesity_data.iloc[[0,10,30],[0,1,2]]

    Gender   Age  Height
0   Female  21.0    1.62
10    Male  26.0    1.85
30    Male  29.0    1.77

In [37]:
obesity_data.at[0,'Age']

21.0

In [38]:
obesity_data.iloc[0,2]

1.62

In [39]:
obesity_data.iat[0,4]

'yes'

In [40]:
obesity_data.iloc[0:5,0:5]

   Gender   Age  Height  Weight family_history
0  Female  21.0    1.62    64.0            yes
1  Female  21.0    1.52    56.0            yes
2    Male  23.0    1.80    77.0            yes
3    Male  27.0    1.80    87.0             no
4    Male  22.0    1.78    89.8             no

In [42]:
obesity_data.loc[obesity_data['Weight']<50]

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
36,Female,22.000000,1.560000,49.000000,no,yes,2.000000,3.000000,Sometimes,no,1.000000,yes,2.000000,0.000000,no,Walking,Normal_Weight
37,Female,21.000000,1.600000,48.000000,no,yes,2.000000,3.000000,Sometimes,no,1.000000,no,1.000000,0.000000,Sometimes,Public_Transportation,Normal_Weight
51,Female,20.000000,1.500000,44.000000,no,yes,2.000000,3.000000,Sometimes,no,1.000000,no,0.000000,0.000000,Sometimes,Automobile,Normal_Weight
60,Female,21.000000,1.550000,49.000000,yes,yes,2.000000,3.000000,Sometimes,no,3.000000,no,3.000000,1.000000,Sometimes,Public_Transportation,Normal_Weight
75,Female,23.000000,1.630000,45.000000,yes,no,3.000000,3.000000,Sometimes,no,3.000000,yes,2.000000,0.000000,no,Public_Transportation,Insufficient_Weight
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
737,Female,19.269079,1.580920,44.753943,no,no,3.000000,2.975362,Frequently,no,1.246822,yes,0.979701,0.000000,Sometimes,Public_Transportation,Insufficient_Weight
738,Female,19.946244,1.603435,45.000000,no,no,3.000000,3.000000,Frequently,no,2.487919,yes,1.230441,0.000000,Sometimes,Public_Transportation,Insufficient_Weight
739,Female,19.639431,1.535350,42.000000,no,yes,3.000000,1.000000,Frequently,no,1.496810,no,0.000000,0.513427,Sometimes,Public_Transportation,Insufficient_Weight
740,Female,19.000000,1.531610,42.000000,no,yes,2.749268,1.394539,Frequently,no,1.322048,no,0.463949,0.800993,Sometimes,Public_Transportation,Insufficient_Weight
741,Female,19.434709,1.525691,42.000000,no,yes,3.000000,1.000000,Frequently,no,1.764055,no,0.000000,0.560887,Sometimes,Public_Transportation,Insufficient_Weight

In [44]:
obesity_data.loc[(obesity_data['Weight']<50) & (obesity_data['Obesity']=='Normal_Weight')]

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
36,Female,22.0,1.56,49.0,no,yes,2.0,3.0,Sometimes,no,1.0,yes,2.0,0.0,no,Walking,Normal_Weight
37,Female,21.0,1.60,48.0,no,yes,2.0,3.0,Sometimes,no,1.0,no,1.0,0.0,Sometimes,Public_Transportation,Normal_Weight
51,Female,20.0,1.50,44.0,no,yes,2.0,3.0,Sometimes,no,1.0,no,0.0,0.0,Sometimes,Automobile,Normal_Weight
60,Female,21.0,1.55,49.0,yes,yes,2.0,3.0,Sometimes,no,3.0,no,3.0,1.0,Sometimes,Public_Transportation,Normal_Weight
94,Female,24.0,1.60,48.0,no,yes,3.0,3.0,Sometimes,no,2.0,no,2.0,0.0,no,Public_Transportation,Normal_Weight
113,Female,22.0,1.50,49.0,yes,no,2.0,1.0,Sometimes,no,2.0,no,3.0,0.0,no,Walking,Normal_Weight
156,Female,35.0,1.53,45.0,yes,no,3.0,3.0,Frequently,no,1.0,no,0.0,1.0,no,Automobile,Normal_Weight
176,Female,18.0,1.57,48.0,yes,yes,3.0,1.0,Always,no,1.0,no,1.0,0.0,no,Public_Transportation,Normal_Weight
180,Female,18.0,1.58,48.0,no,yes,2.0,3.0,Sometimes,no,2.0,no,1.0,0.0,no,Public_Transportation,Normal_Weight
218,Female,21.0,1.50,42.3,yes,no,1.0,1.0,Sometimes,no,2.0,no,3.0,0.0,no,Public_Transportation,Normal_Weight
234,Female,19.0,1.59,49.0,yes,yes,2.0,1.0,no,no,2.0,no,2.0,0.0,no,Public_Transportation,Normal_Weight
244,Female,21.0,1.54,49.0,yes,no,2.0,1.0,Sometimes,no,2.0,yes,2.0,0.0,Sometimes,Public_Transportation,Normal_Weight
253,Female,26.0,1.59,47.0,yes,yes,2.0,1.0,Sometimes,no,2.0,no,0.0,2.0,Sometimes,Public_Transportation,Normal_Weight
303,Female,16.0,1.57,49.0,no,yes,2.0,4.0,Always,no,2.0,no,0.0,1.0,Sometimes,Public_Transportation,Normal_Weight
307,Female,23.0,1.59,48.0,yes,yes,2.0,1.0,Frequently,no,1.0,no,0.0,2.0,Sometimes,Public_Transportation,Normal_Weight
318,Female,25.0,1.56,45.0,no,yes,2.0,3.0,Sometimes,no,1.0,no,0.0,0.0,Sometimes,Public_Transportation,Normal_Weight
346,Female,21.0,1.54,47.0,yes,no,3.0,3.0,Always,no,1.0,no,2.0,0.0,no,Public_Transportation,Normal_Weight
359,Female,33.0,1.56,48.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,1.0,0.0,Sometimes,Public_Transportation,Normal_Weight
385,Female,16.0,1.55,45.0,no,yes,2.0,3.0,Frequently,no,2.0,no,1.0,1.0,no,Public_Transportation,Normal_Weight
445,Female,19.0,1.51,45.0,no,yes,2.0,4.0,Sometimes,no,1.0,no,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
457,Female,19.0,1.50,45.0,no,yes,2.0,3.0,Sometimes,no,1.0,no,0.0,0.0,Sometimes,Public_Transportation,Normal_Weight
497,Male,20.0,1.56,45.0,no,no,2.0,3.0,Sometimes,no,2.0,no,1.0,1.0,Sometimes,Public_Transportation,Normal_Weight

In [45]:
obesity_data.loc[obesity_data['Obesity'].str.startswith('Normal')]

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
0,Female,21.0,1.62,64.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight
1,Female,21.0,1.52,56.0,yes,no,3.0,3.0,Sometimes,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
2,Male,23.0,1.80,77.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight
5,Male,29.0,1.62,53.0,no,yes,2.0,3.0,Sometimes,no,2.0,no,0.0,0.0,Sometimes,Automobile,Normal_Weight
6,Female,23.0,1.50,55.0,yes,yes,3.0,3.0,Sometimes,no,2.0,no,1.0,0.0,Sometimes,Motorbike,Normal_Weight
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
491,Male,25.0,1.66,68.0,no,yes,2.0,3.0,Sometimes,yes,1.0,no,1.0,1.0,Sometimes,Public_Transportation,Normal_Weight
493,Male,20.0,1.80,65.0,no,yes,2.0,3.0,Frequently,no,1.0,no,2.0,0.0,Sometimes,Motorbike,Normal_Weight
494,Female,18.0,1.67,66.0,no,yes,3.0,3.0,Sometimes,no,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Normal_Weight
495,Male,19.0,1.80,60.0,yes,yes,3.0,1.0,Always,no,1.0,yes,0.0,0.0,no,Motorbike,Normal_Weight
497,Male,20.0,1.56,45.0,no,no,2.0,3.0,Sometimes,no,2.0,no,1.0,1.0,Sometimes,Public_Transportation,Normal_Weight

In [46]:
obesity_data.loc[obesity_data['Obesity'].str.endswith('Weight')]

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
0,Female,21.000000,1.620000,64.000000,yes,no,2.000000,3.000000,Sometimes,no,2.000000,no,0.000000,1.000000,no,Public_Transportation,Normal_Weight
1,Female,21.000000,1.520000,56.000000,yes,no,3.000000,3.000000,Sometimes,yes,3.000000,yes,3.000000,0.000000,Sometimes,Public_Transportation,Normal_Weight
2,Male,23.000000,1.800000,77.000000,yes,no,2.000000,3.000000,Sometimes,no,2.000000,no,2.000000,1.000000,Frequently,Public_Transportation,Normal_Weight
5,Male,29.000000,1.620000,53.000000,no,yes,2.000000,3.000000,Sometimes,no,2.000000,no,0.000000,0.000000,Sometimes,Automobile,Normal_Weight
6,Female,23.000000,1.500000,55.000000,yes,yes,3.000000,3.000000,Sometimes,no,2.000000,no,1.000000,0.000000,Sometimes,Motorbike,Normal_Weight
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
740,Female,19.000000,1.531610,42.000000,no,yes,2.749268,1.394539,Frequently,no,1.322048,no,0.463949,0.800993,Sometimes,Public_Transportation,Insufficient_Weight
741,Female,19.434709,1.525691,42.000000,no,yes,3.000000,1.000000,Frequently,no,1.764055,no,0.000000,0.560887,Sometimes,Public_Transportation,Insufficient_Weight
742,Male,18.000000,1.719827,52.289828,yes,yes,1.202075,3.000000,Sometimes,no,1.927976,no,0.023574,1.747256,Sometimes,Public_Transportation,Insufficient_Weight
743,Male,18.381382,1.722547,53.783977,yes,yes,2.000000,3.131032,Sometimes,no,2.072194,no,1.487987,2.000000,Sometimes,Public_Transportation,Insufficient_Weight
744,Male,18.000000,1.738702,50.248677,yes,yes,1.871213,3.000000,Sometimes,no,1.283738,no,0.684879,1.487223,Sometimes,Public_Transportation,Insufficient_Weight

In [49]:
obesity_data.loc[:,'SMOKE']='yes'

In [50]:
obesity_data

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity,Smoke
0,Female,21.000000,1.620000,64.000000,yes,no,2.0,3.0,Sometimes,yes,2.000000,no,0.000000,1.000000,no,Public_Transportation,Normal_Weight,yes
1,Female,21.000000,1.520000,56.000000,yes,no,3.0,3.0,Sometimes,yes,3.000000,yes,3.000000,0.000000,Sometimes,Public_Transportation,Normal_Weight,yes
2,Male,23.000000,1.800000,77.000000,yes,no,2.0,3.0,Sometimes,yes,2.000000,no,2.000000,1.000000,Frequently,Public_Transportation,Normal_Weight,yes
3,Male,27.000000,1.800000,87.000000,no,no,3.0,3.0,Sometimes,yes,2.000000,no,2.000000,0.000000,Frequently,Walking,Overweight_Level_I,yes
4,Male,22.000000,1.780000,89.800000,no,no,2.0,1.0,Sometimes,yes,2.000000,no,0.000000,0.000000,Sometimes,Public_Transportation,Overweight_Level_II,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2106,Female,20.976842,1.710730,131.408528,yes,yes,3.0,3.0,Sometimes,yes,1.728139,no,1.676269,0.906247,Sometimes,Public_Transportation,Obesity_Type_III,yes
2107,Female,21.982942,1.748584,133.742943,yes,yes,3.0,3.0,Sometimes,yes,2.005130,no,1.341390,0.599270,Sometimes,Public_Transportation,Obesity_Type_III,yes
2108,Female,22.524036,1.752206,133.689352,yes,yes,3.0,3.0,Sometimes,yes,2.054193,no,1.414209,0.646288,Sometimes,Public_Transportation,Obesity_Type_III,yes
2109,Female,24.361936,1.739450,133.346641,yes,yes,3.0,3.0,Sometimes,yes,2.852339,no,1.139107,0.586035,Sometimes,Public_Transportation,Obesity_Type_III,yes
2110,Female,23.664709,1.738836,133.472641,yes,yes,3.0,3.0,Sometimes,yes,2.863513,no,1.026452,0.714137,Sometimes,Public_Transportation,Obesity_Type_III,yes

In [51]:
obesity_data.loc[:]

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity,Smoke
0,Female,21.000000,1.620000,64.000000,yes,no,2.0,3.0,Sometimes,yes,2.000000,no,0.000000,1.000000,no,Public_Transportation,Normal_Weight,yes
1,Female,21.000000,1.520000,56.000000,yes,no,3.0,3.0,Sometimes,yes,3.000000,yes,3.000000,0.000000,Sometimes,Public_Transportation,Normal_Weight,yes
2,Male,23.000000,1.800000,77.000000,yes,no,2.0,3.0,Sometimes,yes,2.000000,no,2.000000,1.000000,Frequently,Public_Transportation,Normal_Weight,yes
3,Male,27.000000,1.800000,87.000000,no,no,3.0,3.0,Sometimes,yes,2.000000,no,2.000000,0.000000,Frequently,Walking,Overweight_Level_I,yes
4,Male,22.000000,1.780000,89.800000,no,no,2.0,1.0,Sometimes,yes,2.000000,no,0.000000,0.000000,Sometimes,Public_Transportation,Overweight_Level_II,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2106,Female,20.976842,1.710730,131.408528,yes,yes,3.0,3.0,Sometimes,yes,1.728139,no,1.676269,0.906247,Sometimes,Public_Transportation,Obesity_Type_III,yes
2107,Female,21.982942,1.748584,133.742943,yes,yes,3.0,3.0,Sometimes,yes,2.005130,no,1.341390,0.599270,Sometimes,Public_Transportation,Obesity_Type_III,yes
2108,Female,22.524036,1.752206,133.689352,yes,yes,3.0,3.0,Sometimes,yes,2.054193,no,1.414209,0.646288,Sometimes,Public_Transportation,Obesity_Type_III,yes
2109,Female,24.361936,1.739450,133.346641,yes,yes,3.0,3.0,Sometimes,yes,2.852339,no,1.139107,0.586035,Sometimes,Public_Transportation,Obesity_Type_III,yes
2110,Female,23.664709,1.738836,133.472641,yes,yes,3.0,3.0,Sometimes,yes,2.863513,no,1.026452,0.714137,Sometimes,Public_Transportation,Obesity_Type_III,yes

In [53]:
obesity_data=pd.read_csv('./obesity_prediction.csv')

In [55]:
obesity_data.shape

(2111, 17)

In [57]:
obesity_data.loc[:]

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
0,Female,21.000000,1.620000,64.000000,yes,no,2.0,3.0,Sometimes,no,2.000000,no,0.000000,1.000000,no,Public_Transportation,Normal_Weight
1,Female,21.000000,1.520000,56.000000,yes,no,3.0,3.0,Sometimes,yes,3.000000,yes,3.000000,0.000000,Sometimes,Public_Transportation,Normal_Weight
2,Male,23.000000,1.800000,77.000000,yes,no,2.0,3.0,Sometimes,no,2.000000,no,2.000000,1.000000,Frequently,Public_Transportation,Normal_Weight
3,Male,27.000000,1.800000,87.000000,no,no,3.0,3.0,Sometimes,no,2.000000,no,2.000000,0.000000,Frequently,Walking,Overweight_Level_I
4,Male,22.000000,1.780000,89.800000,no,no,2.0,1.0,Sometimes,no,2.000000,no,0.000000,0.000000,Sometimes,Public_Transportation,Overweight_Level_II
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2106,Female,20.976842,1.710730,131.408528,yes,yes,3.0,3.0,Sometimes,no,1.728139,no,1.676269,0.906247,Sometimes,Public_Transportation,Obesity_Type_III
2107,Female,21.982942,1.748584,133.742943,yes,yes,3.0,3.0,Sometimes,no,2.005130,no,1.341390,0.599270,Sometimes,Public_Transportation,Obesity_Type_III
2108,Female,22.524036,1.752206,133.689352,yes,yes,3.0,3.0,Sometimes,no,2.054193,no,1.414209,0.646288,Sometimes,Public_Transportation,Obesity_Type_III
2109,Female,24.361936,1.739450,133.346641,yes,yes,3.0,3.0,Sometimes,no,2.852339,no,1.139107,0.586035,Sometimes,Public_Transportation,Obesity_Type_III
2110,Female,23.664709,1.738836,133.472641,yes,yes,3.0,3.0,Sometimes,no,2.863513,no,1.026452,0.714137,Sometimes,Public_Transportation,Obesity_Type_III

In [58]:
obesity_data.iloc[:]

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
0,Female,21.000000,1.620000,64.000000,yes,no,2.0,3.0,Sometimes,no,2.000000,no,0.000000,1.000000,no,Public_Transportation,Normal_Weight
1,Female,21.000000,1.520000,56.000000,yes,no,3.0,3.0,Sometimes,yes,3.000000,yes,3.000000,0.000000,Sometimes,Public_Transportation,Normal_Weight
2,Male,23.000000,1.800000,77.000000,yes,no,2.0,3.0,Sometimes,no,2.000000,no,2.000000,1.000000,Frequently,Public_Transportation,Normal_Weight
3,Male,27.000000,1.800000,87.000000,no,no,3.0,3.0,Sometimes,no,2.000000,no,2.000000,0.000000,Frequently,Walking,Overweight_Level_I
4,Male,22.000000,1.780000,89.800000,no,no,2.0,1.0,Sometimes,no,2.000000,no,0.000000,0.000000,Sometimes,Public_Transportation,Overweight_Level_II
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2106,Female,20.976842,1.710730,131.408528,yes,yes,3.0,3.0,Sometimes,no,1.728139,no,1.676269,0.906247,Sometimes,Public_Transportation,Obesity_Type_III
2107,Female,21.982942,1.748584,133.742943,yes,yes,3.0,3.0,Sometimes,no,2.005130,no,1.341390,0.599270,Sometimes,Public_Transportation,Obesity_Type_III
2108,Female,22.524036,1.752206,133.689352,yes,yes,3.0,3.0,Sometimes,no,2.054193,no,1.414209,0.646288,Sometimes,Public_Transportation,Obesity_Type_III
2109,Female,24.361936,1.739450,133.346641,yes,yes,3.0,3.0,Sometimes,no,2.852339,no,1.139107,0.586035,Sometimes,Public_Transportation,Obesity_Type_III
2110,Female,23.664709,1.738836,133.472641,yes,yes,3.0,3.0,Sometimes,no,2.863513,no,1.026452,0.714137,Sometimes,Public_Transportation,Obesity_Type_III

In [59]:
obesity_data.head()

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
0,Female,21.0,1.62,64.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight
1,Female,21.0,1.52,56.0,yes,no,3.0,3.0,Sometimes,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
2,Male,23.0,1.80,77.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight
3,Male,27.0,1.80,87.0,no,no,3.0,3.0,Sometimes,no,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I
4,Male,22.0,1.78,89.8,no,no,2.0,1.0,Sometimes,no,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II

In [60]:
obesity_data.loc[[2,3],['Height']]=1.81

In [62]:
obesity_data.head()

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
0,Female,21.0,1.62,64.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight
1,Female,21.0,1.52,56.0,yes,no,3.0,3.0,Sometimes,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
2,Male,23.0,1.81,77.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight
3,Male,27.0,1.81,87.0,no,no,3.0,3.0,Sometimes,no,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I
4,Male,22.0,1.78,89.8,no,no,2.0,1.0,Sometimes,no,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II

In [63]:
obesity_data.iloc[[0],[4]]="may be"

In [64]:
obesity_data.head()

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
0,Female,21.0,1.62,64.0,may be,no,2.0,3.0,Sometimes,no,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight
1,Female,21.0,1.52,56.0,yes,no,3.0,3.0,Sometimes,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
2,Male,23.0,1.81,77.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight
3,Male,27.0,1.81,87.0,no,no,3.0,3.0,Sometimes,no,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I
4,Male,22.0,1.78,89.8,no,no,2.0,1.0,Sometimes,no,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II

In [66]:
def increment_age_by_5(x):
    return x+5
    
obesity_data['Age']=obesity_data['Age'].apply(increment_age_by_5)

obesity_data.head()

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
0,Female,26.0,1.62,64.0,may be,no,2.0,3.0,Sometimes,no,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight
1,Female,26.0,1.52,56.0,yes,no,3.0,3.0,Sometimes,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
2,Male,28.0,1.81,77.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight
3,Male,32.0,1.81,87.0,no,no,3.0,3.0,Sometimes,no,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I
4,Male,27.0,1.78,89.8,no,no,2.0,1.0,Sometimes,no,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II

In [67]:
obesity_data['Age']=obesity_data['Age'].apply(lambda x:x+5)

obesity_data['Age']

0       31.000000
1       31.000000
2       33.000000
3       37.000000
4       32.000000
          ...
2106    30.976842
2107    31.982942
2108    32.524036
2109    34.361936
2110    33.664709
Name: Age, Length: 2111, dtype: float64

In [68]:
obesity_data['Age']=obesity_data['Age'].apply(lambda x :x-5)
obesity_data['Age']

0       26.000000
1       26.000000
2       28.000000
3       32.000000
4       27.000000
          ...
2106    25.976842
2107    26.982942
2108    27.524036
2109    29.361936
2110    28.664709
Name: Age, Length: 2111, dtype: float64

In [78]:
obesity_data=pd.read_csv('./obesity_prediction.csv')

In [79]:
obesity_data['Age Category']=obesity_data['Age'].apply(lambda x :'very young' if x<30 else 'Not Young')

In [80]:
obesity_data.head()

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity,Age Category
0,Female,21.0,1.62,64.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight,very young
1,Female,21.0,1.52,56.0,yes,no,3.0,3.0,Sometimes,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight,very young
2,Male,23.0,1.80,77.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight,very young
3,Male,27.0,1.80,87.0,no,no,3.0,3.0,Sometimes,no,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I,very young
4,Male,22.0,1.78,89.8,no,no,2.0,1.0,Sometimes,no,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II,very young

In [81]:
import numpy as np

In [82]:
obesity_data['New Age Category']=np.where(obesity_data['Age']<30 ,'Very Young','Not Yonge')

In [83]:
obesity_data.head(20)

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity,Age Category,New Age Category
0,Female,21.0,1.62,64.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight,very young,Very Young
1,Female,21.0,1.52,56.0,yes,no,3.0,3.0,Sometimes,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight,very young,Very Young
2,Male,23.0,1.80,77.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight,very young,Very Young
3,Male,27.0,1.80,87.0,no,no,3.0,3.0,Sometimes,no,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I,very young,Very Young
4,Male,22.0,1.78,89.8,no,no,2.0,1.0,Sometimes,no,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II,very young,Very Young
5,Male,29.0,1.62,53.0,no,yes,2.0,3.0,Sometimes,no,2.0,no,0.0,0.0,Sometimes,Automobile,Normal_Weight,very young,Very Young
6,Female,23.0,1.50,55.0,yes,yes,3.0,3.0,Sometimes,no,2.0,no,1.0,0.0,Sometimes,Motorbike,Normal_Weight,very young,Very Young
7,Male,22.0,1.64,53.0,no,no,2.0,3.0,Sometimes,no,2.0,no,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight,very young,Very Young
8,Male,24.0,1.78,64.0,yes,yes,3.0,3.0,Sometimes,no,2.0,no,1.0,1.0,Frequently,Public_Transportation,Normal_Weight,very young,Very Young
9,Male,22.0,1.72,68.0,yes,yes,2.0,3.0,Sometimes,no,2.0,no,1.0,1.0,no,Public_Transportation,Normal_Weight,very young,Very Young
10,Male,26.0,1.85,105.0,yes,yes,3.0,3.0,Frequently,no,3.0,no,2.0,2.0,Sometimes,Public_Transportation,Obesity_Type_I,very young,Very Young
11,Female,21.0,1.72,80.0,yes,yes,2.0,3.0,Frequently,no,2.0,yes,2.0,1.0,Sometimes,Public_Transportation,Overweight_Level_II,very young,Very Young
12,Male,22.0,1.65,56.0,no,no,3.0,3.0,Sometimes,no,3.0,no,2.0,0.0,Sometimes,Public_Transportation,Normal_Weight,very young,Very Young
13,Male,41.0,1.80,99.0,no,yes,2.0,3.0,Sometimes,no,2.0,no,2.0,1.0,Frequently,Automobile,Obesity_Type_I,Not Young,Not Yonge
14,Male,23.0,1.77,60.0,yes,yes,3.0,1.0,Sometimes,no,1.0,no,1.0,1.0,Sometimes,Public_Transportation,Normal_Weight,very young,Very Young
15,Female,22.0,1.70,66.0,yes,no,3.0,3.0,Always,no,2.0,yes,2.0,1.0,Sometimes,Public_Transportation,Normal_Weight,very young,Very Young
16,Male,27.0,1.93,102.0,yes,yes,2.0,1.0,Sometimes,no,1.0,no,1.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II,very young,Very Young
17,Female,29.0,1.53,78.0,no,yes,2.0,1.0,Sometimes,no,2.0,no,0.0,0.0,no,Automobile,Obesity_Type_I,very young,Very Young
18,Female,30.0,1.71,82.0,yes,yes,3.0,4.0,Frequently,yes,1.0,no,0.0,0.0,no,Automobile,Overweight_Level_II,Not Young,Not Yonge
19,Female,23.0,1.65,70.0,yes,no,2.0,1.0,Sometimes,no,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_I,very young,Very Young

In [84]:
obesity_data.insert(2,'BMI' , 20)

In [86]:
obesity_data.loc[:]

,Gender,Age,BMI,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity,Age Category,New Age Category
0,Female,21.000000,20,1.620000,64.000000,yes,no,2.0,3.0,Sometimes,no,2.000000,no,0.000000,1.000000,no,Public_Transportation,Normal_Weight,very young,Very Young
1,Female,21.000000,20,1.520000,56.000000,yes,no,3.0,3.0,Sometimes,yes,3.000000,yes,3.000000,0.000000,Sometimes,Public_Transportation,Normal_Weight,very young,Very Young
2,Male,23.000000,20,1.800000,77.000000,yes,no,2.0,3.0,Sometimes,no,2.000000,no,2.000000,1.000000,Frequently,Public_Transportation,Normal_Weight,very young,Very Young
3,Male,27.000000,20,1.800000,87.000000,no,no,3.0,3.0,Sometimes,no,2.000000,no,2.000000,0.000000,Frequently,Walking,Overweight_Level_I,very young,Very Young
4,Male,22.000000,20,1.780000,89.800000,no,no,2.0,1.0,Sometimes,no,2.000000,no,0.000000,0.000000,Sometimes,Public_Transportation,Overweight_Level_II,very young,Very Young
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2106,Female,20.976842,20,1.710730,131.408528,yes,yes,3.0,3.0,Sometimes,no,1.728139,no,1.676269,0.906247,Sometimes,Public_Transportation,Obesity_Type_III,very young,Very Young
2107,Female,21.982942,20,1.748584,133.742943,yes,yes,3.0,3.0,Sometimes,no,2.005130,no,1.341390,0.599270,Sometimes,Public_Transportation,Obesity_Type_III,very young,Very Young
2108,Female,22.524036,20,1.752206,133.689352,yes,yes,3.0,3.0,Sometimes,no,2.054193,no,1.414209,0.646288,Sometimes,Public_Transportation,Obesity_Type_III,very young,Very Young
2109,Female,24.361936,20,1.739450,133.346641,yes,yes,3.0,3.0,Sometimes,no,2.852339,no,1.139107,0.586035,Sometimes,Public_Transportation,Obesity_Type_III,very young,Very Young
2110,Female,23.664709,20,1.738836,133.472641,yes,yes,3.0,3.0,Sometimes,no,2.863513,no,1.026452,0.714137,Sometimes,Public_Transportation,Obesity_Type_III,very young,Very Young

In [88]:
obesity_data.drop(columns='BMI')

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity,Age Category,New Age Category
0,Female,21.000000,1.620000,64.000000,yes,no,2.0,3.0,Sometimes,no,2.000000,no,0.000000,1.000000,no,Public_Transportation,Normal_Weight,very young,Very Young
1,Female,21.000000,1.520000,56.000000,yes,no,3.0,3.0,Sometimes,yes,3.000000,yes,3.000000,0.000000,Sometimes,Public_Transportation,Normal_Weight,very young,Very Young
2,Male,23.000000,1.800000,77.000000,yes,no,2.0,3.0,Sometimes,no,2.000000,no,2.000000,1.000000,Frequently,Public_Transportation,Normal_Weight,very young,Very Young
3,Male,27.000000,1.800000,87.000000,no,no,3.0,3.0,Sometimes,no,2.000000,no,2.000000,0.000000,Frequently,Walking,Overweight_Level_I,very young,Very Young
4,Male,22.000000,1.780000,89.800000,no,no,2.0,1.0,Sometimes,no,2.000000,no,0.000000,0.000000,Sometimes,Public_Transportation,Overweight_Level_II,very young,Very Young
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2106,Female,20.976842,1.710730,131.408528,yes,yes,3.0,3.0,Sometimes,no,1.728139,no,1.676269,0.906247,Sometimes,Public_Transportation,Obesity_Type_III,very young,Very Young
2107,Female,21.982942,1.748584,133.742943,yes,yes,3.0,3.0,Sometimes,no,2.005130,no,1.341390,0.599270,Sometimes,Public_Transportation,Obesity_Type_III,very young,Very Young
2108,Female,22.524036,1.752206,133.689352,yes,yes,3.0,3.0,Sometimes,no,2.054193,no,1.414209,0.646288,Sometimes,Public_Transportation,Obesity_Type_III,very young,Very Young
2109,Female,24.361936,1.739450,133.346641,yes,yes,3.0,3.0,Sometimes,no,2.852339,no,1.139107,0.586035,Sometimes,Public_Transportation,Obesity_Type_III,very young,Very Young
2110,Female,23.664709,1.738836,133.472641,yes,yes,3.0,3.0,Sometimes,no,2.863513,no,1.026452,0.714137,Sometimes,Public_Transportation,Obesity_Type_III,very young,Very Young

In [89]:
obesity_data.head()

,Gender,Age,BMI,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity,Age Category,New Age Category
0,Female,21.0,20,1.62,64.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight,very young,Very Young
1,Female,21.0,20,1.52,56.0,yes,no,3.0,3.0,Sometimes,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight,very young,Very Young
2,Male,23.0,20,1.80,77.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight,very young,Very Young
3,Male,27.0,20,1.80,87.0,no,no,3.0,3.0,Sometimes,no,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I,very young,Very Young
4,Male,22.0,20,1.78,89.8,no,no,2.0,1.0,Sometimes,no,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II,very young,Very Young

In [91]:
obesity_data.drop(columns='BMI',inplace=True)

In [92]:
obesity_data.head()

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity,Age Category,New Age Category
0,Female,21.0,1.62,64.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight,very young,Very Young
1,Female,21.0,1.52,56.0,yes,no,3.0,3.0,Sometimes,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight,very young,Very Young
2,Male,23.0,1.80,77.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight,very young,Very Young
3,Male,27.0,1.80,87.0,no,no,3.0,3.0,Sometimes,no,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I,very young,Very Young
4,Male,22.0,1.78,89.8,no,no,2.0,1.0,Sometimes,no,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II,very young,Very Young

In [93]:
obesity_data.insert(2,'BMI',obesity_data['Weight']/obesity_data['Height']**2)

In [94]:
obesity_data.head()

,Gender,Age,BMI,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity,Age Category,New Age Category
0,Female,21.0,24.386526,1.62,64.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight,very young,Very Young
1,Female,21.0,24.238227,1.52,56.0,yes,no,3.0,3.0,Sometimes,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight,very young,Very Young
2,Male,23.0,23.765432,1.80,77.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight,very young,Very Young
3,Male,27.0,26.851852,1.80,87.0,no,no,3.0,3.0,Sometimes,no,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I,very young,Very Young
4,Male,22.0,28.342381,1.78,89.8,no,no,2.0,1.0,Sometimes,no,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II,very young,Very Young

In [100]:
df1=pd.DataFrame({
   'id' :[1,2,3,4],
    'name':['Abhi','Amit' ,'Cloud','GenAI']    
})

df2= pd.DataFrame({
   'id' : [3,4,5,6],
    'course':['GenAi','LLD','MLD','LLM']

})

inner_result=pd.merge(df1,df2,how='inner',on='id')

inner_result

   id   name course
0   3  Cloud  GenAi
1   4  GenAI    LLD

In [101]:
outer_join=pd.merge(df1,df2,how='outer',on='id')
outer_join

   id   name course
0   1   Abhi    NaN
1   2   Amit    NaN
2   3  Cloud  GenAi
3   4  GenAI    LLD
4   5    NaN    MLD
5   6    NaN    LLM

In [102]:
left_result=pd.merge(df1,df2,how='left', on ='id')
left_result

   id   name course
0   1   Abhi    NaN
1   2   Amit    NaN
2   3  Cloud  GenAi
3   4  GenAI    LLD

In [104]:
result_concat= pd.concat([df1,df2],axis=0,ignore_index=True)
result_concat

   id   name course
0   1   Abhi    NaN
1   2   Amit    NaN
2   3  Cloud    NaN
3   4  GenAI    NaN
4   3    NaN  GenAi
5   4    NaN    LLD
6   5    NaN    MLD
7   6    NaN    LLM

In [105]:
result_concat= pd.concat([df1,df2],axis=1)
result_concat

   id   name  id course
0   1   Abhi   3  GenAi
1   2   Amit   4    LLD
2   3  Cloud   5    MLD
3   4  GenAI   6    LLM

In [106]:
result_concat.isna()

      id   name     id  course
0  False  False  False   False
1  False  False  False   False
2  False  False  False   False
3  False  False  False   False

In [107]:
result_concat= pd.concat([df1,df2],axis=0,ignore_index=True)
result_concat

   id   name course
0   1   Abhi    NaN
1   2   Amit    NaN
2   3  Cloud    NaN
3   4  GenAI    NaN
4   3    NaN  GenAi
5   4    NaN    LLD
6   5    NaN    MLD
7   6    NaN    LLM

In [108]:
result_concat.isna()

      id   name  course
0  False  False    True
1  False  False    True
2  False  False    True
3  False  False    True
4  False   True   False
5  False   True   False
6  False   True   False
7  False   True   False

In [110]:
result_concat.isna().sum()

id        0
name      4
course    4
dtype: int64

In [111]:
obesity_data.loc[0,'Age']=np.nan

In [112]:
obesity_data.head()

,Gender,Age,BMI,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity,Age Category,New Age Category
0,Female,NaN,24.386526,1.62,64.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight,very young,Very Young
1,Female,21.0,24.238227,1.52,56.0,yes,no,3.0,3.0,Sometimes,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight,very young,Very Young
2,Male,23.0,23.765432,1.80,77.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight,very young,Very Young
3,Male,27.0,26.851852,1.80,87.0,no,no,3.0,3.0,Sometimes,no,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I,very young,Very Young
4,Male,22.0,28.342381,1.78,89.8,no,no,2.0,1.0,Sometimes,no,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II,very young,Very Young

In [118]:
obesity_data.loc[0,'Age']=np.nan
obesity_data.loc[0 ,'SMOKE']=np.nan
obesity_data.loc[2,'Age']=np.nan

In [119]:
obesity_data.fillna(0)

,Gender,Age,BMI,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity,Age Category,New Age Category
0,Female,0.000000,24.386526,1.620000,64.000000,yes,no,2.0,3.0,Sometimes,0,2.000000,no,0.000000,1.000000,no,Public_Transportation,Normal_Weight,very young,Very Young
1,Female,21.000000,24.238227,1.520000,56.000000,yes,no,3.0,3.0,Sometimes,yes,3.000000,yes,3.000000,0.000000,Sometimes,Public_Transportation,Normal_Weight,very young,Very Young
2,Male,0.000000,23.765432,1.800000,77.000000,yes,no,2.0,3.0,Sometimes,no,2.000000,no,2.000000,1.000000,Frequently,Public_Transportation,Normal_Weight,very young,Very Young
3,Male,27.000000,26.851852,1.800000,87.000000,no,no,3.0,3.0,Sometimes,no,2.000000,no,2.000000,0.000000,Frequently,Walking,Overweight_Level_I,very young,Very Young
4,Male,22.000000,28.342381,1.780000,89.800000,no,no,2.0,1.0,Sometimes,no,2.000000,no,0.000000,0.000000,Sometimes,Public_Transportation,Overweight_Level_II,very young,Very Young
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2106,Female,20.976842,44.901475,1.710730,131.408528,yes,yes,3.0,3.0,Sometimes,no,1.728139,no,1.676269,0.906247,Sometimes,Public_Transportation,Obesity_Type_III,very young,Very Young
2107,Female,21.982942,43.741923,1.748584,133.742943,yes,yes,3.0,3.0,Sometimes,no,2.005130,no,1.341390,0.599270,Sometimes,Public_Transportation,Obesity_Type_III,very young,Very Young
2108,Female,22.524036,43.543817,1.752206,133.689352,yes,yes,3.0,3.0,Sometimes,no,2.054193,no,1.414209,0.646288,Sometimes,Public_Transportation,Obesity_Type_III,very young,Very Young
2109,Female,24.361936,44.071535,1.739450,133.346641,yes,yes,3.0,3.0,Sometimes,no,2.852339,no,1.139107,0.586035,Sometimes,Public_Transportation,Obesity_Type_III,very young,Very Young
2110,Female,23.664709,44.144338,1.738836,133.472641,yes,yes,3.0,3.0,Sometimes,no,2.863513,no,1.026452,0.714137,Sometimes,Public_Transportation,Obesity_Type_III,very young,Very Young

In [120]:
obesity_data['Age']=obesity_data['Age'].fillna(20)

In [121]:
obesity_data.head()

,Gender,Age,BMI,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity,Age Category,New Age Category
0,Female,20.0,24.386526,1.62,64.0,yes,no,2.0,3.0,Sometimes,NaN,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight,very young,Very Young
1,Female,21.0,24.238227,1.52,56.0,yes,no,3.0,3.0,Sometimes,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight,very young,Very Young
2,Male,20.0,23.765432,1.80,77.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight,very young,Very Young
3,Male,27.0,26.851852,1.80,87.0,no,no,3.0,3.0,Sometimes,no,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I,very young,Very Young
4,Male,22.0,28.342381,1.78,89.8,no,no,2.0,1.0,Sometimes,no,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II,very young,Very Young

In [124]:

obesity_data.loc[0,'Age']=np.nan
obesity_data['Age']=obesity_data['Age'].fillna(obesity_data['Age'].mean())

In [125]:
obesity_data.head()

,Gender,Age,BMI,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity,Age Category,New Age Category
0,Female,24.312748,24.386526,1.62,64.0,yes,no,2.0,3.0,Sometimes,NaN,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight,very young,Very Young
1,Female,21.000000,24.238227,1.52,56.0,yes,no,3.0,3.0,Sometimes,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight,very young,Very Young
2,Male,20.000000,23.765432,1.80,77.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight,very young,Very Young
3,Male,27.000000,26.851852,1.80,87.0,no,no,3.0,3.0,Sometimes,no,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I,very young,Very Young
4,Male,22.000000,28.342381,1.78,89.8,no,no,2.0,1.0,Sometimes,no,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II,very young,Very Young

In [126]:
obesity_data.groupby('Gender')['Height'].mean()

Gender
Female    1.643298
Male      1.758690
Name: Height, dtype: float64

In [127]:
obesity_data.groupby('Gender')['Height'].sum()

Gender
Female    1713.959615
Male      1878.281278
Name: Height, dtype: float64

In [128]:
obesity_data.groupby('Gender')['Height'].agg(['sum','mean'])

                sum      mean
Gender
Female  1713.959615  1.643298
Male    1878.281278  1.758690